Repository madeinoz67/maker-hub, pull requests merged in 2021-05, with the labels that each got.

#52 fixes issue #51
  README.md
Labels: documentation

#86 adds favicon and logo to the docs site
  docs/img/favicon.ico
  docs/img/logo.svg
  mkdocs.yml
Labels: module: mkdocs

#89 Adds VSCode remote development container
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .gitignore
  .vscode/settings.json
Labels: pr: python, type: enhancement
